name: Mobile Tests - iOS and Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run iOS Tests
      run: npx appium --platform-name iOS --app ./path/to/your.app --device-name "iPhone Simulator"
    
  android:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
    
    - name: Set up Android Emulator
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        echo "no" | sdkmanager --update
        sdkmanager "platform-tools" "tools" "build-tools;29.0.2" "platforms;android-29"
        echo "no" | avdmanager create avd --force -n test -k "system-images;android-29;google_apis;x86_64"
        sudo $ANDROID_HOME/tools/emulator -avd test -no-window -gpu off &
        sleep 60  # Aguarda o emulador iniciar
    
    - name: Run Android Tests
      run: npx appium --platform-name Android --app ./path/to/your.apk --device-name "Android Emulator"
