name: Mobile Tests - iOS and Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run iOS Tests
      run: npx appium --platform-name iOS --app <path_to_your_app> --device-name "iPhone Simulator"
    
  android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Set up Android Emulator
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        echo "no" | android update sdk --no-ui --filter "tools,platform-tools,build-tools,android-29"
        echo "no" | android create avd --force -n test -t android-29 --abi x86_64
    
    - name: Run Android Tests
      run: npx appium --platform-name Android --app <path_to_your_app> --device-name "Android Emulator"
