name: Mobile Tests - iOS and Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Run iOS Tests
        run: |
          echo "Booting iOS Simulator"
          xcrun simctl boot "iPhone 14" || true
          sleep 30
          echo "Running iOS Tests"
          npx appium --platform-name iOS --app ./path/to/your.app --device-name "iPhone 14"

  android:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
          sdkmanager --install "platform-tools" "build-tools;31.0.0" "platforms;android-31" "system-images;android-31;google_apis;x86_64"
          sdkmanager --licenses

      - name: Start Android Emulator
        run: |
          echo "no" | avdmanager create avd --force -n test -k "system-images;android-31;google_apis;x86_64"
          emulator -avd test -no-window -gpu off &
          sleep 60

      - name: Run Android Tests
        run: |
          echo "Running Android Tests"
          npx appium --platform-name Android --app ./path/to/your.apk --device-name "Android Emulator"
